# Generated by Django 4.2.10 on 2024-03-02 01:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='category-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product-images'),
        ),
    ]
