# Generated by Django 4.2.10 on 2024-03-02 02:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product-images'),
        ),
    ]
