# Generated by Django 4.2.10 on 2024-03-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_facebook_url_brand_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('XS', 'XS'), ('Memory_Foam', 'Memory_Foam'), ('Polyurethane_Foam ', 'Polyurethane_Foam '), ('Polyester_Fiberfill', 'Polyester_Fiberfill')], default='XS', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
