# Generated by Django 4.2.10 on 2024-03-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_material_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
    ]
