# Generated by Django 4.2.10 on 2024-03-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_colors_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('Latex', 'Latex'), ('Memory_Foam', 'Memory_Foam'), ('Polyurethane_Foam ', 'Polyurethane_Foam '), ('Polyester_Fiberfill', 'Polyester_Fiberfill')], default='Latex', max_length=255),
        ),
    ]
